pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo "Descargando código desde GitHub..."
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo "Construyendo proyecto..."
                script {
                    if (isUnix()) {
                        sh '''
                            cd playlist
                            ./mvnw clean package -DskipTests
                        '''
                    } else {
                        bat '''
                            cd playlist
                            mvnw.cmd clean package -DskipTests
                        '''
                    }
                }
            }
        }

        stage('Test') {
            steps {
                echo "Ejecutando tests..."
                script {
                    if (isUnix()) {
                        sh '''
                            cd playlist
                            ./mvnw test
                        '''
                    } else {
                        bat '''
                            cd playlist
                            mvnw.cmd test
                        '''
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    if (isUnix()) {
                        echo 'Ejecutando deploy en Mac...'
                        sh '''
                            cd playlist
                            chmod +x scripts/deploy-mac.sh
                            ./scripts/deploy-mac.sh
                        '''
                    } else {
                        echo 'Ejecutando deploy en Windows...'
                        bat '''
                            cd playlist
                            .\\scripts\\deploy-windows.bat
                        '''
                    }
                }
            }
        }
    }
}

