pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo "Descargando código desde GitHub..."
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo "Construyendo proyecto..."
                bat '''
                    cd playlist
                    mvnw.cmd clean package -DskipTests
                '''
            }
        }

        stage('Test') {
            steps {
                echo "Ejecutando tests..."
                bat '''
                    cd playlist
                    mvnw.cmd test
                '''
            }
        }

        
        stage('Deploy') {
            steps {
                echo 'Ejecutando deploy en Windows...'
                bat 'cd playlist && .\\scripts\\deploy_windows.bat'
            }
        }


    }
}
